server:
  port: 8011

spring:
  redis:
    host: 188.131.228.155
    password: yuntuzhilian
  dubbo:
    appname: user-consumer
    registry: zookeeper://127.0.0.1:2181
#  mail:
#    # 发送邮件服务器
#    host: smtp.qq.com
#    # QQ邮箱
#    username: 861024581@qq.com
#    # 客户端授权码 wmmvfqpigiedbcba
#    password: wmmvfqpigiedbcba
#    default-encoding: utf-8
#    port: 995
#    properties:
#      mail:
#        smtp:
#          auth: true
#          socketFactory:
#            class: javax.net.ssl.SSLSocketFactory
#            port: 465

swagger:
  basePackage: com.ytzl.gotrip.controller
  title: 用户模块API接口
  description:  用户模块对外API接口

